language: node_js

node_js: 4.1

env:
  global:
    - secure: AyQ0abZa7PqB2PLZ7CBScD8RxMdU6mcYd8+0hOShK1QMzw4XwuSmc/3hSKXXuKqgIK5bDXIgtSn/h26MZx6qgmWorfkOc3tfc9ngtiGZqMm/5V3gx54cbk2fGy4BScz0etfLM8GbQrad+EPLvPFRPLq3zwBVvx2uyPgYIVJLBhk=
    - secure: cwxsyqvgIgcOvGAKRTvQn5Ki8G0RKp6PvcQwwr8mwRGpfKPQSRlGY0FdRiJKM3XH/u2LIMdv8a5KGq6zBaHGsh5uS0S8053nOrC2W+jJCLH3+SRDop6a4yv7MS6ZzOBbwWsmrbJ5zHN8PbssyslFC/dJuZ6uEIFRM4Jo+dqZ+Q4=

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls

notifications:
  email:
    on_failure: change
    on_success: change
